version: '2'
services:
  marklogic-server:
    image: store/marklogicdb/marklogic-server:10.0-2-dev-ubi
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
      - TZ=Europe/Prague
    ports:
      - 7997-8015:7997-8015
  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - "4040:4040"
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    volumes:
      - ./data:/opt/spark-data
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "constraint:node==myMasterNode"
  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./data:/opt/spark-data
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==myWorkerNode1"
